### ISSUE TITLE
Markdown File Change

### ISSUE THREAD

**Issue by twhay** [gerwinf/simple-marketplace#1]
In the markdown file, change 
Clone the repo using git clone git@github.com:gerwinf/simple-marketplace.git

To
Clone the repo using git clone git clone https://github.com/gerwinf/simple-marketplace.git

This will allow for the repo to be cloned using the command line (on a mac at least)

**Comment by gerwinf** [comment]
Done. Previous line was compatible with Ubuntu but your suggestion works as well.
